#!/usr/bin/env bash

if ! cargo clippy --help >/dev/null 2>&1; then
    echo 'Installing clippy (https://github.com/rust-lang/rust-clippy)' \
        > $AUTOHOOK_STDOUT

    if ! rustup component add clippy > $AUTOHOOK_STDOUT 2> $AUTOHOOK_STDERR; then
        echo 'Failed to install clippy. See output above'
        exit 1
    fi
fi

cargo clippy --manifest-path="$AUTOHOOK_REPO_ROOT/Cargo.toml" \
    > $AUTOHOOK_STDOUT \
    2> $AUTOHOOK_STDERR
exit $?
